# fly.toml app configuration file generated for ark-nova-stats-worker on 2024-08-03T19:09:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ark-nova-stats-worker'
primary_region = 'ewr'

[build]
  image = 'shaldengeki/ark-nova-stats-worker:latest'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
