# fly.toml app configuration file generated for ark-nova-stats-api on 2024-07-23T01:00:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ark-nova-stats-api'
primary_region = 'ewr'

[build]
  image = 'shaldengeki/ark-nova-stats-api:latest'

[deploy]
  release_command = "/ark_nova_stats/api/migrations/binary"

[env]
  API_PORT = '5000'
  FLASK_APP = 'app.py'
  FLASK_DEBUG = 'false'
  FRONTEND_HOST = 'arknova.ouguo.us'
  FRONTEND_PORT = ''
  FRONTEND_PROTOCOL = 'https'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
