import GameLog, { emptyGameLog } from './GameLog';
import User, { emptyUser } from './User';

type GameStatistics = {
    user: User;
    bgaTableId: number;
    rank: number;
    score: number;
    thinkingTime: number;
    startingPosition: number;
    breaksTriggered: number;
    triggeredEnd: boolean;
    mapId: number;
    actionsBuild: number;
    actionsAnimals: number;
    actionsCards: number;
    actionsAssociation: number;
    actionsSponsors: number;
    xTokensGained: number;
    xActions: number;
    xTokensUsed: number;
    moneyGained: number;
    moneyGainedThroughIncome: number;
    moneySpentOnAnimals: number;
    moneySpentOnEnclosures: number;
    moneySpentOnDonations: number;
    moneySpentOnPlayingCardsFromReputationRange: number;
    cardsDrawnFromDeck: number;
    cardsDrawnFromReputationRange: number;
    cardsSnapped: number;
    cardsDiscarded: number;
    playedSponsors: number;
    playedAnimals: number;
    releasedAnimals: number;
    associationWorkers: number;
    associationDonations: number;
    associationReputationActions: number;
    associationPartnerZooActions: number;
    associationUniversityActions: number;
    associationConservationProjectActions: number;
    builtEnclosures: number;
    builtKiosks: number;
    builtPavilions: number;
    builtUniqueBuildings: number;
    hexesCovered: number;
    hexesEmpty: number;
    upgradedActionCards: number;
    upgradedAnimals: boolean;
    upgradedBuild: boolean;
    upgradedCards: boolean;
    upgradedSponsors: boolean;
    upgradedAssociation: boolean;
    iconsAfrica: number;
    iconsEurope: number;
    iconsAsia: number;
    iconsAustralia: number;
    iconsAmericas: number;
    iconsBird: number;
    iconsPredator: number;
    iconsHerbivore: number;
    iconsBear: number;
    iconsReptile: number;
    iconsPrimate: number;
    iconsPettingZoo: number;
    iconsSeaAnimal: number;
    iconsWater: number;
    iconsRock: number;
    iconsScience: number;
}

export const emptyGameStatistics: GameStatistics = {
    user: emptyUser,
    bgaTableId: 0,
    rank: 0,
    score: 0,
    thinkingTime: 0,
    startingPosition: 0,
    breaksTriggered: 0,
    triggeredEnd: false,
    mapId: 0,
    actionsBuild: 0,
    actionsAnimals: 0,
    actionsCards: 0,
    actionsAssociation: 0,
    actionsSponsors: 0,
    xTokensGained: 0,
    xActions: 0,
    xTokensUsed: 0,
    moneyGained: 0,
    moneyGainedThroughIncome: 0,
    moneySpentOnAnimals: 0,
    moneySpentOnEnclosures: 0,
    moneySpentOnDonations: 0,
    moneySpentOnPlayingCardsFromReputationRange: 0,
    cardsDrawnFromDeck: 0,
    cardsDrawnFromReputationRange: 0,
    cardsSnapped: 0,
    cardsDiscarded: 0,
    playedSponsors: 0,
    playedAnimals: 0,
    releasedAnimals: 0,
    associationWorkers: 0,
    associationDonations: 0,
    associationReputationActions: 0,
    associationPartnerZooActions: 0,
    associationUniversityActions: 0,
    associationConservationProjectActions: 0,
    builtEnclosures: 0,
    builtKiosks: 0,
    builtPavilions: 0,
    builtUniqueBuildings: 0,
    hexesCovered: 0,
    hexesEmpty: 0,
    upgradedActionCards: 0,
    upgradedAnimals: false,
    upgradedBuild: false,
    upgradedCards: false,
    upgradedSponsors: false,
    upgradedAssociation: false,
    iconsAfrica: 0,
    iconsEurope: 0,
    iconsAsia: 0,
    iconsAustralia: 0,
    iconsAmericas: 0,
    iconsBird: 0,
    iconsPredator: 0,
    iconsHerbivore: 0,
    iconsBear: 0,
    iconsReptile: 0,
    iconsPrimate: 0,
    iconsPettingZoo: 0,
    iconsSeaAnimal: 0,
    iconsWater: 0,
    iconsRock: 0,
    iconsScience: 0,
}

export default GameStatistics;
