load("@rules_python//python:defs.bzl", "py_binary")
load("//tools/build_rules/worker:defs.bzl", "worker")

worker(
    name = "worker",
    registry = "docker.io",
    repository = "shaldengeki/skeleton-worker",
    tag = "latest",
    deps = ["//skeleton:config_py"],
)

py_binary(
    name = "app",
    srcs = ["app.py"],
    visibility = ["//:__subpackages__"],
    deps = ["//skeleton:config_py"],
)
