load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "in_memory_game_state",
    srcs = ["in_memory_game_state.go"],
    importpath = "github.com/shaldengeki/monorepo/games/checkers/game_state/in_memory_game_state",
    visibility = ["//visibility:public"],
    deps = [
        "//games/checkers/game_state",
        "//games/checkers/proto:proto_go_proto",
    ],
)
