# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
    skip:
        - buildifier
        - buildifier-lint

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v5.0.0
        hooks:
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-yaml
            -   id: no-commit-to-branch
                args: [--branch, staging, --branch, main]
    -   repo: https://github.com/psf/black
        rev: 25.1.0
        hooks:
            -   id: black
    -   repo: https://github.com/pycqa/isort
        rev: 6.0.0
        hooks:
            -   id: isort
                name: isort (python)
    -   repo: https://github.com/keith/pre-commit-buildifier
        rev: 8.0.1
        hooks:
        -   id: buildifier
        -   id: buildifier-lint
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v1.15.0
        hooks:
            -   id: mypy
                additional_dependencies:
                    - types-requests==2.31.0.20240218
                    - types-protobuf==5.27.0.20240626
    -   repo: https://github.com/pre-commit/mirrors-eslint
        rev: 'v9.20.1'
        hooks:
            -   id: eslint
                files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
                types: [file]
                args: ["--fix", "--ignore-pattern", "ark_nova_stats/extension/*"]
                additional_dependencies:
                    -   eslint@8.38.0
                    -   eslint-config-standard@17.0.0
                    -   eslint-plugin-import@2.27.5
                    -   eslint-plugin-node@11.1.0
                    -   eslint-plugin-promise@6.1.1
                    -   eslint-plugin-react@7.32.2
                    -   eslint-config-react-app
