# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
    skip:
        - buildifier
        - buildifier-lint

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.6.0
        hooks:
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-yaml
            -   id: no-commit-to-branch
                args: [--branch, staging, --branch, main]
    -   repo: https://github.com/psf/black
        rev: 24.4.2
        hooks:
            -   id: black
    -   repo: https://github.com/pycqa/isort
        rev: 5.13.2
        hooks:
            -   id: isort
                name: isort (python)
    -   repo: https://github.com/keith/pre-commit-buildifier
        rev: 6.4.0.1
        hooks:
        -   id: buildifier
        -   id: buildifier-lint
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v1.11.0
        hooks:
            -   id: mypy
                additional_dependencies: [types-requests==2.31.0.20240218]
    -   repo: https://github.com/pre-commit/mirrors-eslint
        rev: 'v9.7.0'
        hooks:
            -   id: eslint
                files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
                types: [file]
                args: ["--fix"]
                additional_dependencies:
                    -   eslint@8.38.0
                    -   eslint-config-standard@17.0.0
                    -   eslint-plugin-import@2.27.5
                    -   eslint-plugin-node@11.1.0
                    -   eslint-plugin-promise@6.1.1
                    -   eslint-plugin-react@7.32.2
                    -   eslint-config-react-app
