version: '3'
services:
  api: &api
    image: shaldengeki/fitbit-challenges-api:latest
    env_file:
      - env/.api.env
    restart: always
    depends_on:
      - pg
  migration:
    <<: *api
    command: [ "/fitbit_challenges/api/migrations/binary", "/fitbit_challenges/api/migrations", "./binary.runfiles/_main/fitbit_challenges/api/migrations/alembic.ini", "upgrade"]
    restart: no
  worker:
    <<: *api
    image: shaldengeki/fitbit-challenges-worker:latest
  pg:
    image: postgres:15-alpine
    restart: always
    env_file:
      - env/.postgres.env
    volumes:
      - fitbit-challenges-pg:/var/lib/postgresql/data
  frontend:
    image: shaldengeki/fitbit-challenges-frontend:latest
    env_file:
      - env/.frontend.env
    restart: always
volumes:
  fitbit-challenges-pg:
    name: fitbit-challenges_fitbit-challenges-pg
