version: "3"
services:
  api: &api
    env_file:
      - env/.api.env
    ports:
      - "5000:5000"
  migration:
    <<: *api
    ports: []
  worker:
    <<: *api
    image: shaldengeki/skeleton-worker:latest
    ports: []
    deploy:
      replicas: 0
  pg:
    env_file:
      - env/.postgres.env
  frontend:
    image: shaldengeki/skeleton-frontend:latest
    env_file:
      - env/.frontend.env
    ports:
      - "5001:80"
