version: '3'
services:
  api:
    build: .
    image: home_api
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=5000
  pg:
    image: postgres:alpine
    restart: always
    ports:
        - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=development
      - POSTGRES_USER=admin
      - POSTGRES_DB=api_development