version: '3'
services:
  api: &api
    image: shaldengeki/ark-nova-stats-api:latest
    env_file:
      - env/.api.env
    restart: always
    depends_on:
      - pg
  migration:
    <<: *api
    command: [ "/ark_nova_stats/api/migrations/binary"]
    restart: "no"
  worker:
    <<: *api
    image: shaldengeki/ark-nova-stats-worker:latest
  pg:
    image: postgres:alpine
    restart: always
    env_file:
      - env/.postgres.env
    volumes:
      - ark-nova-stats-pg:/var/lib/postgresql/data
  frontend:
    image: shaldengeki/ark-nova-stats-frontend:latest
    env_file:
      - env/.frontend.env
    restart: always
volumes:
  ark-nova-stats-pg:
