version: "3"
services:
  api: &api
    env_file:
      - env/.api.env
    ports:
      - "5000:5000"
  migration:
    <<: *api
    ports: []
  worker:
    <<: *api
    image: shaldengeki/ark-nova-stats-worker:latest
    ports: []
  pg:
    env_file:
      - env/.postgres.env
    ports:
      - "5432:5432"
  frontend:
    image: shaldengeki/ark-nova-stats-frontend:latest
    env_file:
      - env/.frontend.env
    ports:
      - "5001:80"
