version: '3'
services:
  api: &api
    image: shaldengeki/fitbit-challenges-api:latest
    ports:
      - "5000:5000"
    env_file:
      - env/.api.prod.env
  migration:
    <<: *api
    ports: []
  worker:
    <<: *api
    ports: []
  pg:
    restart: always
    env_file:
      - env/.postgres.prod.env
  frontend:
    image: shaldengeki/fitbit-challenges-frontend:latest
    ports:
      - "5001:80"
    env_file:
      - env/.frontend.prod.env
