version: '3'
services:
  api:
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/src/app
    environment:
      - PORT=5000
      - FLASK_ENV=development
      - DB_HOST=pg
      - DB_USERNAME=admin
      - DB_PASSWORD=development
      - DATABASE_NAME=api_development
      - FRONTEND_HOST=localhost
      - FRONTEND_PORT=5001
  migration:
    volumes:
      - ./api:/usr/src/app
    environment:
      - FLASK_ENV=development
      - DB_HOST=pg
      - DB_USERNAME=admin
      - DB_PASSWORD=development
      - DATABASE_NAME=api_development
  pg:
    environment:
      - POSTGRES_PASSWORD=development
      - POSTGRES_USER=admin
      - POSTGRES_DB=api_development
  frontend:
    command: ["npm", "run", "build-and-start"]
    ports:
      - "5001:5001"
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment:
      - PORT=5001
      - REACT_APP_API_HOST=localhost
      - REACT_APP_API_PORT=5000
      - REACT_APP_API_PROTOCOL=http
