# fly.toml app configuration file generated for frontend-autumn-morning-9289 on 2024-07-22T20:23:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frontend-autumn-morning-9289'
primary_region = 'ewr'

[build]
  image = 'shaldengeki/fitbit-challenges-frontend:latest'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
