version: '3'
services:
  api: &api
    image: shaldengeki/proto-registry-api:latest
    ports:
      - "5000:5000"
    env_file:
      - env/.api.env
    restart: always
    depends_on:
      - pg
  migration:
    <<: *api
    image: shaldengeki/proto-registry-api-migrations:latest
    ports: []
    restart: no
  pg:
    image: postgres:15-alpine
    restart: always
    env_file:
      - env/.postgres.env
    volumes:
      - proto_registry-pg:/var/lib/postgresql/data
volumes:
  proto_registry-pg:
    name: proto_registry_proto_registry-pg
