#!/usr/bin/env bash

set -uxo pipefail

bazel run //:requirements.update && git add requirements.lock.txt MODULE.bazel.lock && git commit -m "bazel run //:requirements.update"
bazel run @@//:gazelle_python_manifest.update && git add gazelle_python.yaml MODULE.bazel.lock && git commit -m "bazel run @@//:gazelle_python_manifest.update"
git push
