#!/usr/bin/env bash

# For development use.
# Rebuilds all the containers for the app and reloads any running containers.

set -euxo pipefail

bazel run api:api_image_image_tarball
bazel run api/migrations:image_tarball

docker compose -f docker-compose.yaml -f docker-compose.override.yaml up --no-deps -d api migration pg
