load("@rules_python//python:defs.bzl", "py_binary")
load("//tools/build_rules/worker:defs.bzl", "worker")

worker(
    name = "worker",
    env = {
        "DATABASE_URL": "test-database-url",
        "FITBIT_CLIENT_ID": "testing",
        "FITBIT_CLIENT_SECRET": "testing",
        "FITBIT_VERIFICATION_CODE": "testing",
    },
    registry = "docker.io",
    repository = "shaldengeki/fitbit-challenges-worker",
    tag = "latest",
    deps = [
        "//fitbit_challenges:config_py",
        "//fitbit_challenges:fitbit_client_py",
        "//fitbit_challenges:models_py",
        "//scripts:wait_for_postgres",
        "@py_deps//graphql_server",
        "@py_deps//requests",
        "@py_deps//sqlalchemy",
    ],
)

py_binary(
    name = "app",
    srcs = ["app.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//fitbit_challenges:config_py",
        "//fitbit_challenges:fitbit_client_py",
        "//fitbit_challenges:models_py",
        "@py_deps//sqlalchemy",
    ],
)
