# fly.toml app configuration file generated for fitbit-challenges-worker on 2024-08-06T04:39:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fitbit-challenges-worker'
primary_region = 'ewr'

[build]
  image = 'shaldengeki/fitbit-challenges-worker:latest'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
