version: '3'
services:
  api: &api
    image: shaldengeki/home-api-api:latest
    env_file:
      - env/.api.env
    restart: always
    depends_on:
      - pg
    environment:
      - API_PORT=5000
      - FLASK_ENV=development
      - DB_HOST=pg
      - DB_USERNAME=admin
      - DB_PASSWORD=development
      - DATABASE_NAME=api_development
      - FRONTEND_HOST=192.168.1.5
      - FRONTEND_PORT=5001
    ports:
      - "5000:5000"
  migration:
    <<: *api
    command: [ "/home_api/api/migrations/binary", "upgrade"]
    restart: no
    depends_on:
      - pg
    ports: []
  pg:
    image: postgres:15-alpine
    restart: always
    env_file:
      - env/.postgres.env
    environment:
      - POSTGRES_PASSWORD=development
      - POSTGRES_USER=admin
      - POSTGRES_DB=api_development
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  frontend:
    image: shaldengeki/home-api-frontend:latest
    env_file:
      - env/.frontend.env
    restart: always
    environment:
      - PORT=5001
      - REACT_APP_API_HOST=192.168.1.5
      - REACT_APP_API_PORT=5000
    ports:
      - "5001:80"
