version: "3"
services:
  api: &api
    env_file:
      - env/.api.env
    ports:
      - "5000:5000"
  migration:
    <<: *api
    ports: []
  pg:
    env_file:
      - env/.postgres.env
  frontend:
    image: shaldengeki/home-api-frontend:latest
    env_file:
      - env/.frontend.env
    ports:
      - "5001:80"
