# fly.toml app configuration file generated for fitbit-challenges-api on 2024-08-02T20:16:37-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fitbit-challenges-api'
primary_region = 'ewr'

[build]
  image = 'shaldengeki/fitbit-challenges-api:latest'

[deploy]
  release_command = '/fitbit_challenges/api/migrations/binary /fitbit_challenges/api/migrations ./binary.runfiles/_main/fitbit_challenges/api/migrations/alembic.ini upgrade'

[env]
  API_PORT = '5000'
  FLASK_APP = 'app.py'
  FLASK_DEBUG = 'false'
  FRONTEND_HOST = 'fitbit.ouguo.us'
  FRONTEND_PORT = ''
  FRONTEND_PROTOCOL = 'https'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
