name: Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint and fix
        uses: hallee/eslint-action@1.0.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Root directory to lint files in.
          source-root: frontend/src
