name: Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: eslint + fix
      uses: getsentry/action-eslint-fix@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
