name: Test

on:
  pull_request:
  push:
    branches: [ main ]
  merge_group:

jobs:
  test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
        working-directory: ./src/javascript/frontend
      - run: npm test
        working-directory: ./src/javascript/frontend
  build-frontend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - test-js
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src/javascript/frontend
          file: ./src/javascript/frontend/Dockerfile.prod.dockerfile
          push: true
          tags: shaldengeki/fitbit-challenges-frontend:latest
