name: Regenerate cache

on:
  schedule:
    # Daily
    - cron: '23 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v4
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
            ~/.cache/bazel-repo
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}-${{ github.sha }}
          # Pull caches from:
          # - The current sha,
          # - The current branch,
          # - base branch
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}-${{ github.sha }}
            ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}-
            ${{ runner.os }}-${{ env.cache-name }}-refs/heads/${{ github.base_ref }}-
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bazel clean
        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc clean --expunge
      - name: bazel test //...
        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
